language: node_js
node_js:
  - 12

before_install:
  - npm install netlify-cli -g

script:
  - npm ci && npm run-script build

deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=build --prod
  on:
    branch: master
